<!DOCTYPE html>
<div class="row">
    <div class="col-sm">
     
    </div>
    <div class="col-sm">
<form action="" method="post" enctype="multipart/form-data">
  <input type="hidden" name="event_number" value="<?php echo $event->event_number;?>">

  <div class="form-group">
    <label>Event name</label>
    <input type="text" name="event_name" class="form-control" id="eventname" placeholder="eventname" required >
  </div>
  
  <div class="form-group">

    <label>Date</label>
    <input type="date" name="event_date" class="form-control" id="datepicker" placeholder="datepicker" min="2018-01-01" max="2019-12-31" required> 
  </div>
  

  <div class="form-group">
    <label>Event detail</label>
    <input type="text" name="event_detail" class="form-control" id="eventdetail" placeholder="eventdetail" required>
  </div>


   <div class="form-group">
    <label>Event Picture</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input" >
          <label class="custom-file-label" >Choose file</label>
    </div>
  </div>

  <button type="submit" class="btn btn-info">Submit</button>
  <a href="<?php echo $this->url->getBaseUri(); ?>/event/show" class="btn btn-warning">Back</a>

</form>
    </div>
    <div class="col-sm">
    </div>
  </div>

  </html>
