<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Phalcon PHP Framework</title>
    
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="css/grayscale.min.css" rel="stylesheet">

  </head>

    <body id="page-top" >

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">

      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="<?php echo$this->url->getBaseUri();?>profile">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<?php echo$this->url->getBaseUri();?>event/show">Event</a>
            </li>

            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<?php echo$this->url->getBaseUri();?>#about">About</a>
            </li>

             <!-- <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li> -->

          </ul>

           <ul class="navbar-nav  navbar-right">     
     <?php if($this->session->has('memberAuthen')) {?> 
      
   
      <li class="nav-item">
              <a class="nav-link rounded js-scroll-trigger" href="<?php echo$this->url->getBaseUri();?>#about"><?php echo $this->session->get('memberEmail');?></a>
     </li>
     <li class="nav-item">
     		<a  class="btn btn-danger navbar-btn" href="<?php echo$this->url->getBaseUri();?>authen/signOut"> Logout </a> 
     </li>  
    <?php } else {?>
      <li class="nav-item">
       <a href="authen" class="btn btn-outline-primary"> Login </a>
      </li>    
     <li class="nav-item">
       <a href="authen/signUp" class="btn btn-outline-info"> Sign Up </a>
      </li>
      <?php }?>
    </ul>
        </div>
      </div>
    </nav>




 <!-- Intro Header -->
 <header class="masthead">
      <div class="intro-body">
        <div class="container"><?php echo $this->getContent(); ?>
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <a href="#about" class="btn btn-circle js-scroll-trigger">
                <i class="fa fa-angle-double-down animated"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </header>


    <!-- About Section -->
    <section id="about" class="content-section text-center">
      <div class="container">
        <div class="row">
          <!-- <div class="mypic"><img src="img/mypic1.jpg"></div><br> -->
          <div class="col-lg-8 mx-auto">
            <br><h2>About</h2>
            <br><p>Kittiya Wisitpongpan</p>
            <br><p>590610604</p>
            
          </div>
        </div>
      </div>
    </section>



  
    <!-- Map Section -->
    <div id="map"></div>

   <!-- Footer -->
   <footer>
      <div class="container text-center">
        <p>Copyright &copy; Your Website 2018</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

   
    <!-- Custom scripts for this template -->
    <script src="js/grayscale.min.js"></script>



  </body>
  
</html>
